### ISSUE TITLE
Roadmap of umzug v2.0

### ISSUE THREAD

**Issue by jukkah** [sequelize/umzug#95]
I'm working on version 2.0. I'll write it with ES2017 so the code will be completely rewritten.
### Features
- [ ] Umzug class
  - [ ] Support built-in storages out of the box with minimal set of parameters.
  - [ ] Support custom storages (#77).
  - [ ] Support globs (#33, #80) in migration paths and dynamic object[](#79).
- [ ] Migration class
  - [ ] Support any kind of migration modules, including ES6 syntax (#85) and dynamic objects (#79).
  - [ ] Add support to squashed migrations (#39).
- [ ] Storage classes
  - [ ] Add built-in storages
    - [x] Storage (formerly NoneStorage)
    - [x] JSONStorage
    - [ ] SequelizeStorage
  - [ ] Save execution timestamp along with migration name (#90).
  - [ ] Act as mutex (#59).
### API
- [x] Make API solid (#50, #32).
- [ ] Ensure backwards compatibility where possible.
### Testing
- [ ] Write unit tests.
- [ ] Write cross unit  = internal integration tests.
- [ ] Write integration tests for Sequelize.
### Documentation
- [ ] Rewrite API documentation (#32).
- [ ] Write usage examples (#84).
- [ ] Write tutorials (#84).
### Other
- [x] Add ESLint.
- [ ] Optimize npm installable bundle.
- [ ] Drop support to node.js < 4. (See [Node LTS strategy](https://github.com/nodejs/LTS))

Comments are welcome. (I work with [my own fork](https://github.com/jukkah/umzug/tree/v2) for a while. Comments are welcome there too.)
